openapi: "3.0.0"
info:
  description: ""
  title: "Delilah Restó"
  version: "1.0.0"
servers: 
  - url: "http://localhost:3000"
components:
  securitySchemes:
    bearerAuth:         
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /user/signUp: 
      post:
        summary: "Create user"
        requestBody: 
          content: 
            application/json:
              schema:
                type: "object"
                properties: 
                  usuario:
                    type: "string"
                  nombreCompleto:
                    type: "string"
                  correo:
                    type: "string"
                  telefono: 
                    type: "string"
                  direccion: 
                    type: "string"
                  contrasena:
                    type: "string"
        responses:
          "201":
            description: "User created"
            content:
              application/json:
                schema:
                  type: "object"
                  properties:
                    token:
                      type: "string"
                    mensaje: 
                      type: "string"
                    user:
                      type: "object"
                      properties: 
                        usuario:
                          type: "string"
                        nombreCompleto:
                          type: "string"
                        correo:
                          type: "string"
                        telefono: 
                          type: "string"
                        direccion: 
                          type: "string"
          "400":
            description: "User exist"
            content:
              application/json:
                schema:
                  type: "object"
                  properties:
                    token: 
                      type: "string"
                    mensaje:
                      type: "string"
          "default":
            description: "Default error, some error happened"
            content:
              application/json:
                schema:
                  type: "object"
                  properties:
                    token: 
                      type: "string"
                    mensaje:
                      type: "string"
  /user/login:
    post: 
      summary: "Login user"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties: 
                usuario: 
                  type: "string"
                contrasena:
                  type: "string"
      responses: 
        "200":
          description: "Login Succeed"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  token:
                    type: "string"
                  usuario:
                    type: "string"
                  nombre_completo:
                    type: "string"
                  correo:
                    type: "string"
                  telefono: 
                    type: "string"
                  direccion: 
                    type: "string"
                  administrador:
                    type: "boolean"
        "400":
          description: "username or password incorrect"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  token:
                    type: "string"
                  mensaje:
                    type: "string"
  /product:
    get:
      security:
        - bearerAuth: []
      summary: "get all products"
      responses:
        "200":
          description: "all products"
          content:
            application/json:
              schema:
                type: "object"
                properties: 
                  productos:
                    type: "array"
                    items: 
                      type: "object"
                      properties:
                        id:
                          type: "number"
                        nombre:
                          type: "string"
                        precio:
                          type: "number"
                        imagen: 
                          type: "string"
        "401":
          description: "authentication errors"
          content:
            application/json:
              schema:
                type: "object"
                properties: 
                  mensaje:
                    type: "string"
        "400":
          description: "some error happend"
          content:
            application/json:
              schema:
                type: "object"
                properties: 
                  mensaje:
                    type: "string"
    post:
      security:
        - bearerAuth: []
      summary: "Create Product"
      requestBody: 
        content:
          application/json:
            schema:
              type: "object"
              properties:
                nombre: 
                  type: "string"
                precio: 
                  type: "number"
                imagen:
                  type: "string"
      responses:
        "201":
          description: "product created"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  mensaje: 
                    type: "string"
        "400":
          description: "some error happend"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  mensaje:
                    type: "string"
        "401":
          description: "authentication errors"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  mensaje:
                    type: "string"
    put: 
      security:
        - bearerAuth: []
      summary: "update product"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                id:
                  type: "number"
                nombre:
                  type: "string"
                precio:
                  type: "number"
                imagen:
                  type: "string"
      responses:
        "200":
          description: "updated product"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  mensaje: 
                    type: "string"
        "400":
          description: "some error happend"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  mensaje:
                    type: "string"
        "401":
          description: "authentication errors"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  mensaje:
                    type: "string"
    delete:
      security:
        - bearerAuth: []
      summary: "delete specific product"
      parameters:
        - name: productId
          in: query
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "delete succesfull"
          content:
            application/json:
              schema:
                type: "object"
                properties: 
                  mensaje:
                    type: "string"
        "400":
          description: "some error happend"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  mensaje:
                    type: "string"
        "401":
          description: "authentication errors"
          content:
            application/json:
              schema:
                type: "object"
                properties: 
                  mensaje:
                    type: "string"
  /order:
    get:
      security:
        - bearerAuth: []
      summary: "get all orders"
      responses:
        "200":
          description: "all orders"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  orders:
                    type: "array"
                    items: 
                      type: "object"
                      properties:
                        numero: 
                          type: "number"
                        estado:
                          type: "string"
                        precio:
                          type: "string"
                        descripcion:
                          type: "string"
                        pago: 
                          type: "number"
                        usuario:
                          type: "string"
                        productos:
                          type: "array"
                          items: 
                            type: "object"
                            properties:
                              id:
                                type: "number"
                              nombre:
                                type: "string"
                              precio:
                                type: "number"
                              cantidad:
                                type: "number"
        "400":
          description: "some error happend"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  mensaje:
                    type: "string"
        "401":
          description: "authentication errors"
          content:
            application/json:
              schema:
                type: "object"
                properties: 
                  mensaje:
                    type: "string"
    post:
      security:
        - bearerAuth: []
      summary: "Create Order"
      requestBody: 
        content:
          application/json:
            schema:
              type: "object"
              properties:
                products:
                  type: "array"
                  items:
                    type: "object"
                    properties:
                      id:
                        type: "number"
                      nombre:
                        type: "string"
                      precio:
                        type: "number"
                      cantidad:
                        type: "number"
      responses:
        "201":
          description: "order created"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  mensaje: 
                    type: "string"
        "401":
          description: "authentication errors"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  mensaje:
                    type: "string"
    put: 
      security:
        - bearerAuth: []
      summary: "update order"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                numero:
                  type: "number"
                estado:
                  type: "string"
      responses:
        "200":
          description: "updated order"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  mensaje: 
                    type: "string"
        "401":
          description: "authentication errors"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  mensaje:
                    type: "string"
        "default":
          description: "Default error, some error happened"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  mensaje:
                    type: "string"
    delete:
      security:
        - bearerAuth: []
      summary: "delete specific order"
      parameters:
        - name: orderId
          in: query
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "delete succesfull"
          content:
            application/json:
              schema:
                type: "object"
                properties: 
                  name: 
                    type: "string"
                  price:
                    type: "number"
        "401":
          description: "authentication errors"
          content:
            application/json:
              schema:
                type: "object"
                properties: 
                  mensaje:
                    type: "string"
  /order/{usuario}:
    get:
      security:
        - bearerAuth: []
      summary: "get specific product"
      parameters:
        - name: usuario
          in: path
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "all products"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  orders:
                    type: "array"
                    items: 
                      type: "object"
                      properties:
                        numero: 
                          type: "number"
                        estado:
                          type: "string"
                        precio:
                          type: "string"
                        descripcion:
                          type: "string"
                        pago: 
                          type: "number"
                        usuario:
                          type: "string"
                        productos:
                          type: "array"
                          items: 
                            type: "object"
                            properties:
                              id:
                                type: "number"
                              nombre:
                                type: "string"
                              precio:
                                type: "number"
                              cantidad:
                                type: "number"
                            
        "400":
          description: "some error happend"
          content:
            application/json:
              schema:
                type: "object"
                properties: 
                  mensaje:
                    type: "string"
        "401":
          description: "authentication errors"
          content:
            application/json:
              schema:
                type: "object"
                properties: 
                  mensaje:
                    type: "string"