openapi: "3.0.0"
info:
  description: ""
  title: "Delilah Restó"
  version: "1.0.0"
servers: 
  - url: "http://localhost:3000"
paths:
  /user/signUp: 
      post:
        summary: "Create user"
        requestBody: 
          content: 
            application/json:
              schema:
                type: "object"
                properties: 
                  usuario:
                    type: "string"
                  nombreCompleto:
                    type: "string"
                  correo:
                    type: "string"
                  telefono: 
                    type: "string"
                  direccion: 
                    type: "string"
                  contrasena:
                    type: "string"
        responses:
          "201":
            description: "User created"
            content:
              application/json:
                schema:
                  type: "object"
                  properties:
                    token:
                      type: "string"
                    mensaje: 
                      type: "string"
                    user:
                      type: "object"
                      properties: 
                        usuario:
                          type: "string"
                        nombreCompleto:
                          type: "string"
                        correo:
                          type: "string"
                        telefono: 
                          type: "string"
                        direccion: 
                          type: "string"
          "400":
            description: "User exist"
            content:
              application/json:
                schema:
                  type: "object"
                  properties:
                    token: 
                      type: "string"
                    mensaje:
                      type: "string"
          "default":
            description: "Default error, some error happened"
            content:
              application/json:
                schema:
                  type: "object"
                  properties:
                    token: 
                      type: "string"
                    mensaje:
                      type: "string"
  /user/login:
    post: 
      summary: "Login user"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties: 
                usuario: 
                  type: "string"
                contrasena:
                  type: "string"
      responses: 
        "200":
          description: "Login Succeed"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  token:
                    type: "string"
                  mensaje:
                    type: "string"
                  data:
                    type: "object"
                    properties: 
                      usuario:
                        type: "string"
                      nombreCompleto:
                        type: "string"
                      correo:
                        type: "string"
                      telefono: 
                        type: "string"
                      direccion: 
                        type: "string"
        "400":
          description: "username or password incorrect"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  token:
                    type: "string"
                  mensaje:
                    type: "string"
        "default":
            description: "Default error, some error happened"
            content:
              application/json:
                schema:
                  type: "object"
                  properties:
                    token: 
                      type: "string"
                    mensaje:
                      type: "string"
  /product:
    get:
      summary: "get all products"
      responses:
        "200":
          description: "all products"
          content:
            application/json:
              schema:
                type: "object"
                properties: 
                  data:
                    type: "array"
                    items: 
                      type: "object"
        "401":
          description: "authentication errors"
          content:
            application/json:
              schema:
                type: "object"
                properties: 
                  mensaje:
                    type: "string"
    post:
      summary: "Create Product"
      requestBody: 
        content:
          application/json:
            schema:
              type: "object"
              properties:
                nombre: 
                  type: "string"
                precio: 
                  type: "number"
                imagen:
                  type: "string"
      responses:
        "201":
          description: "product created"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  mensaje: 
                    type: "string"
        "400":
          description: "product alredy exist"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  mensaje:
                    type: "string"
        "401":
          description: "authentication errors"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  mensaje:
                    type: "string"
    put: 
      summary: "update product"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                nombre:
                  type: "string"
                precio:
                  type: "number"
                imagen:
                  type: "string"
      responses:
        "200":
          description: "updated product"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  mensaje: 
                    type: "string"
        "401":
          description: "authentication errors"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  mensaje:
                    type: "string"
        "default":
          description: "Default error, some error happened"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  mensaje:
                    type: "string"
  /product/{nombre}:
    get:
      summary: "get specific product"
      parameters:
        - name: nombre
          in: path
          description: ID of pet to fetch
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "all products"
          content:
            application/json:
              schema:
                type: "object"
                properties: 
                  name: 
                    type: "string"
                  price:
                    type: "number"
        "401":
          description: "authentication errors"
          content:
            application/json:
              schema:
                type: "object"
                properties: 
                  mensaje:
                    type: "string"
    delete:
      summary: "delete specific product"
      parameters:
        - name: nombre
          in: path
          description: ID of pet to fetch
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "all products"
          content:
            application/json:
              schema:
                type: "object"
                properties: 
                  name: 
                    type: "string"
                  price:
                    type: "number"
        "401":
          description: "authentication errors"
          content:
            application/json:
              schema:
                type: "object"
                properties: 
                  mensaje:
                    type: "string"
  /order:
    get:
      summary: "get all orders"
      responses:
        "200":
          description: "all orders"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  data: 
                    type: "array"
                    items:
                      type: "object"
        "401":
          description: "authentication errors"
          content:
            application/json:
              schema:
                type: "object"
                properties: 
                  mensaje:
                    type: "string"
    post:
      summary: "Create Order"
      requestBody: 
        content:
          application/json:
            schema:
              type: "object"
              properties:
                date: 
                  type: "number"
                products:
                  type: "array"
                  items:
                    type: "object"
                pago: 
                  type: "number"
      responses:
        "201":
          description: "order created"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  mensaje: 
                    type: "string"
        "401":
          description: "authentication errors"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  mensaje:
                    type: "string"
    put: 
      summary: "update order"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                id:
                  type: "string"
                state:
                  type: "string"
      responses:
        "200":
          description: "updated order"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  mensaje: 
                    type: "string"
        "401":
          description: "authentication errors"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  mensaje:
                    type: "string"
        "default":
          description: "Default error, some error happened"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  mensaje:
                    type: "string"
  /order/{usuario}:
    get:
      summary: "get specific product"
      parameters:
        - name: usuario
          in: path
          description: ID of pet to fetch
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "all products"
          content:
            application/json:
              schema:
                type: "object"
                properties: 
                  name: 
                    type: "string"
                  price:
                    type: "number"
        "401":
          description: "authentication errors"
          content:
            application/json:
              schema:
                type: "object"
                properties: 
                  mensaje:
                    type: "string"